/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.10.1.112 */
/* Module Version: 4.2 */
/* C:\lscc\diamond\3.10_x64\ispfpga\bin\nt64\scuba.exe -w -n muladdsub -lang verilog -synth lse -bb -arch sa5p00 -type dspmadd -widtha 18 -widthb 18 -widthp 37 -area -maddsub -signed -rega0 -rega1 -rega0clk CLK0 -rega0ce CE0 -rega0rst RST0 -rega1clk CLK0 -rega1ce CE0 -rega1rst RST0 -regb0 -regb1 -regb0clk CLK0 -regb0ce CE0 -regb0rst RST0 -regb1clk CLK0 -regb1ce CE0 -regb1rst RST0 -pipe_full -regp0 -regp1 -regas0 -regas1 -regp0clk CLK0 -regp0rst RST0 -regp0ce CE1 -regp1clk CLK0 -regp1rst RST0 -regp1ce CE1 -regas0clk CLK0 -regas0rst RST0 -regas0ce CE1 -regas1clk CLK0 -regas1rst RST0 -regas1ce CE1 -rego -regoclk CLK0 -regorst RST0 -regoce CE2 -clk0 -ce0 -ce1 -ce2 -rst0 -fdc C:/FPGA/scratch/lseaddsub/mas/muladdsub/muladdsub.fdc  */
/* Wed May 09 18:05:14 2018 */

`timescale 1 ns / 1 ps


module muladdsub (CLK0, CE0, CE1, CE2, RST0, ADDNSUB, A0, A1, B0, B1,
    SUM)/* synthesis NGD_DRC_MASK=1 */;
    input wire CLK0;
    input wire CE0;
    input wire CE1;
    input wire CE2;
    input wire RST0;
    input wire ADDNSUB;
    input wire [17:0] A0, A1, B0, B1;
    output wire [35:0] SUM;

`ifdef VERILATE

    reg [17:0] A0_r, A1_r, B0_r, B1_r;

    always @(posedge CLK0 or posedge RST0)
        if (RST0) begin
            A0_r <= 18'b0;
            A1_r <= 18'b0;
            B0_r <= 18'b0;
            B1_r <= 18'b0;
        end else if (CE0) begin
            A0_r <= A0;
            A1_r <= A1;
            B0_r <= B0;
            B1_r <= B1;
        end

    reg [35:0] AB0_r, AB1_r;

    always @(posedge CLK0 or posedge RST0)
        if (RST0) begin
            AB0_r <= 36'b0;
            AB1_r <= 36'b0;
        end else if (CE1) begin
            AB0_r <= $signed(A0_r) * $signed(B0_r);
            AB1_r <= $signed(A1_r) * $signed(B1_r);
        end

    reg [35:0] AB_r;

    always @(posedge CLK0 or posedge RST0)
        if (RST0)
            AB_r <= 36'b0;
        else if (CE2)
            AB_r <= (
                ADDNSUB
                    ? $signed(AB0_r) + $signed(AB1_r)
                    : $signed(AB0_r) - $signed(AB1_r)
            );

        assign SUM = AB_r;
`else

    wire muladdsub_alu_signedr_1_0;
    wire muladdsub_alu_output_r_1_0_53;
    wire muladdsub_alu_output_r_1_0_52;
    wire muladdsub_alu_output_r_1_0_51;
    wire muladdsub_alu_output_r_1_0_50;
    wire muladdsub_alu_output_r_1_0_49;
    wire muladdsub_alu_output_r_1_0_48;
    wire muladdsub_alu_output_r_1_0_47;
    wire muladdsub_alu_output_r_1_0_46;
    wire muladdsub_alu_output_r_1_0_45;
    wire muladdsub_alu_output_r_1_0_44;
    wire muladdsub_alu_output_r_1_0_43;
    wire muladdsub_alu_output_r_1_0_42;
    wire muladdsub_alu_output_r_1_0_41;
    wire muladdsub_alu_output_r_1_0_40;
    wire muladdsub_alu_output_r_1_0_39;
    wire muladdsub_alu_output_r_1_0_38;
    wire muladdsub_alu_output_r_1_0_37;
    wire muladdsub_alu_output_r_1_0_36;
    wire muladdsub_alu_output_r_1_0_35;
    wire muladdsub_alu_output_r_1_0_34;
    wire muladdsub_alu_output_r_1_0_33;
    wire muladdsub_alu_output_r_1_0_32;
    wire muladdsub_alu_output_r_1_0_31;
    wire muladdsub_alu_output_r_1_0_30;
    wire muladdsub_alu_output_r_1_0_29;
    wire muladdsub_alu_output_r_1_0_28;
    wire muladdsub_alu_output_r_1_0_27;
    wire muladdsub_alu_output_r_1_0_26;
    wire muladdsub_alu_output_r_1_0_25;
    wire muladdsub_alu_output_r_1_0_24;
    wire muladdsub_alu_output_r_1_0_23;
    wire muladdsub_alu_output_r_1_0_22;
    wire muladdsub_alu_output_r_1_0_21;
    wire muladdsub_alu_output_r_1_0_20;
    wire muladdsub_alu_output_r_1_0_19;
    wire muladdsub_alu_output_r_1_0_18;
    wire muladdsub_alu_output_r_1_0_17;
    wire muladdsub_alu_output_r_1_0_16;
    wire muladdsub_alu_output_r_1_0_15;
    wire muladdsub_alu_output_r_1_0_14;
    wire muladdsub_alu_output_r_1_0_13;
    wire muladdsub_alu_output_r_1_0_12;
    wire muladdsub_alu_output_r_1_0_11;
    wire muladdsub_alu_output_r_1_0_10;
    wire muladdsub_alu_output_r_1_0_9;
    wire muladdsub_alu_output_r_1_0_8;
    wire muladdsub_alu_output_r_1_0_7;
    wire muladdsub_alu_output_r_1_0_6;
    wire muladdsub_alu_output_r_1_0_5;
    wire muladdsub_alu_output_r_1_0_4;
    wire muladdsub_alu_output_r_1_0_3;
    wire muladdsub_alu_output_r_1_0_2;
    wire muladdsub_alu_output_r_1_0_1;
    wire muladdsub_alu_output_r_1_0_0;
    wire muladdsub_alu_signedcin_1_0;
    wire addsub_inv;
    wire muladdsub_alu_in_cin_1_0_53;
    wire muladdsub_alu_in_cin_1_0_52;
    wire muladdsub_alu_in_cin_1_0_51;
    wire muladdsub_alu_in_cin_1_0_50;
    wire muladdsub_alu_in_cin_1_0_49;
    wire muladdsub_alu_in_cin_1_0_48;
    wire muladdsub_alu_in_cin_1_0_47;
    wire muladdsub_alu_in_cin_1_0_46;
    wire muladdsub_alu_in_cin_1_0_45;
    wire muladdsub_alu_in_cin_1_0_44;
    wire muladdsub_alu_in_cin_1_0_43;
    wire muladdsub_alu_in_cin_1_0_42;
    wire muladdsub_alu_in_cin_1_0_41;
    wire muladdsub_alu_in_cin_1_0_40;
    wire muladdsub_alu_in_cin_1_0_39;
    wire muladdsub_alu_in_cin_1_0_38;
    wire muladdsub_alu_in_cin_1_0_37;
    wire muladdsub_alu_in_cin_1_0_36;
    wire muladdsub_alu_in_cin_1_0_35;
    wire muladdsub_alu_in_cin_1_0_34;
    wire muladdsub_alu_in_cin_1_0_33;
    wire muladdsub_alu_in_cin_1_0_32;
    wire muladdsub_alu_in_cin_1_0_31;
    wire muladdsub_alu_in_cin_1_0_30;
    wire muladdsub_alu_in_cin_1_0_29;
    wire muladdsub_alu_in_cin_1_0_28;
    wire muladdsub_alu_in_cin_1_0_27;
    wire muladdsub_alu_in_cin_1_0_26;
    wire muladdsub_alu_in_cin_1_0_25;
    wire muladdsub_alu_in_cin_1_0_24;
    wire muladdsub_alu_in_cin_1_0_23;
    wire muladdsub_alu_in_cin_1_0_22;
    wire muladdsub_alu_in_cin_1_0_21;
    wire muladdsub_alu_in_cin_1_0_20;
    wire muladdsub_alu_in_cin_1_0_19;
    wire muladdsub_alu_in_cin_1_0_18;
    wire muladdsub_alu_in_cin_1_0_17;
    wire muladdsub_alu_in_cin_1_0_16;
    wire muladdsub_alu_in_cin_1_0_15;
    wire muladdsub_alu_in_cin_1_0_14;
    wire muladdsub_alu_in_cin_1_0_13;
    wire muladdsub_alu_in_cin_1_0_12;
    wire muladdsub_alu_in_cin_1_0_11;
    wire muladdsub_alu_in_cin_1_0_10;
    wire muladdsub_alu_in_cin_1_0_9;
    wire muladdsub_alu_in_cin_1_0_8;
    wire muladdsub_alu_in_cin_1_0_7;
    wire muladdsub_alu_in_cin_1_0_6;
    wire muladdsub_alu_in_cin_1_0_5;
    wire muladdsub_alu_in_cin_1_0_4;
    wire muladdsub_alu_in_cin_1_0_3;
    wire muladdsub_alu_in_cin_1_0_2;
    wire muladdsub_alu_in_cin_1_0_1;
    wire muladdsub_alu_in_cin_1_0_0;
    wire muladdsub_0_mult_out_rob_0_17;
    wire muladdsub_0_mult_out_roa_0_17;
    wire muladdsub_0_mult_out_rob_0_16;
    wire muladdsub_0_mult_out_roa_0_16;
    wire muladdsub_0_mult_out_rob_0_15;
    wire muladdsub_0_mult_out_roa_0_15;
    wire muladdsub_0_mult_out_rob_0_14;
    wire muladdsub_0_mult_out_roa_0_14;
    wire muladdsub_0_mult_out_rob_0_13;
    wire muladdsub_0_mult_out_roa_0_13;
    wire muladdsub_0_mult_out_rob_0_12;
    wire muladdsub_0_mult_out_roa_0_12;
    wire muladdsub_0_mult_out_rob_0_11;
    wire muladdsub_0_mult_out_roa_0_11;
    wire muladdsub_0_mult_out_rob_0_10;
    wire muladdsub_0_mult_out_roa_0_10;
    wire muladdsub_0_mult_out_rob_0_9;
    wire muladdsub_0_mult_out_roa_0_9;
    wire muladdsub_0_mult_out_rob_0_8;
    wire muladdsub_0_mult_out_roa_0_8;
    wire muladdsub_0_mult_out_rob_0_7;
    wire muladdsub_0_mult_out_roa_0_7;
    wire muladdsub_0_mult_out_rob_0_6;
    wire muladdsub_0_mult_out_roa_0_6;
    wire muladdsub_0_mult_out_rob_0_5;
    wire muladdsub_0_mult_out_roa_0_5;
    wire muladdsub_0_mult_out_rob_0_4;
    wire muladdsub_0_mult_out_roa_0_4;
    wire muladdsub_0_mult_out_rob_0_3;
    wire muladdsub_0_mult_out_roa_0_3;
    wire muladdsub_0_mult_out_rob_0_2;
    wire muladdsub_0_mult_out_roa_0_2;
    wire muladdsub_0_mult_out_rob_0_1;
    wire muladdsub_0_mult_out_roa_0_1;
    wire muladdsub_0_mult_out_rob_0_0;
    wire muladdsub_0_mult_out_roa_0_0;
    wire muladdsub_0_mult_out_p_0_35;
    wire muladdsub_0_mult_out_p_0_34;
    wire muladdsub_0_mult_out_p_0_33;
    wire muladdsub_0_mult_out_p_0_32;
    wire muladdsub_0_mult_out_p_0_31;
    wire muladdsub_0_mult_out_p_0_30;
    wire muladdsub_0_mult_out_p_0_29;
    wire muladdsub_0_mult_out_p_0_28;
    wire muladdsub_0_mult_out_p_0_27;
    wire muladdsub_0_mult_out_p_0_26;
    wire muladdsub_0_mult_out_p_0_25;
    wire muladdsub_0_mult_out_p_0_24;
    wire muladdsub_0_mult_out_p_0_23;
    wire muladdsub_0_mult_out_p_0_22;
    wire muladdsub_0_mult_out_p_0_21;
    wire muladdsub_0_mult_out_p_0_20;
    wire muladdsub_0_mult_out_p_0_19;
    wire muladdsub_0_mult_out_p_0_18;
    wire muladdsub_0_mult_out_p_0_17;
    wire muladdsub_0_mult_out_p_0_16;
    wire muladdsub_0_mult_out_p_0_15;
    wire muladdsub_0_mult_out_p_0_14;
    wire muladdsub_0_mult_out_p_0_13;
    wire muladdsub_0_mult_out_p_0_12;
    wire muladdsub_0_mult_out_p_0_11;
    wire muladdsub_0_mult_out_p_0_10;
    wire muladdsub_0_mult_out_p_0_9;
    wire muladdsub_0_mult_out_p_0_8;
    wire muladdsub_0_mult_out_p_0_7;
    wire muladdsub_0_mult_out_p_0_6;
    wire muladdsub_0_mult_out_p_0_5;
    wire muladdsub_0_mult_out_p_0_4;
    wire muladdsub_0_mult_out_p_0_3;
    wire muladdsub_0_mult_out_p_0_2;
    wire muladdsub_0_mult_out_p_0_1;
    wire muladdsub_0_mult_out_p_0_0;
    wire muladdsub_0_mult_out_signedp_0;
    wire muladdsub_0_mult_out_rob_1_17;
    wire muladdsub_0_mult_out_roa_1_17;
    wire muladdsub_0_mult_out_rob_1_16;
    wire muladdsub_0_mult_out_roa_1_16;
    wire muladdsub_0_mult_out_rob_1_15;
    wire muladdsub_0_mult_out_roa_1_15;
    wire muladdsub_0_mult_out_rob_1_14;
    wire muladdsub_0_mult_out_roa_1_14;
    wire muladdsub_0_mult_out_rob_1_13;
    wire muladdsub_0_mult_out_roa_1_13;
    wire muladdsub_0_mult_out_rob_1_12;
    wire muladdsub_0_mult_out_roa_1_12;
    wire muladdsub_0_mult_out_rob_1_11;
    wire muladdsub_0_mult_out_roa_1_11;
    wire muladdsub_0_mult_out_rob_1_10;
    wire muladdsub_0_mult_out_roa_1_10;
    wire muladdsub_0_mult_out_rob_1_9;
    wire muladdsub_0_mult_out_roa_1_9;
    wire muladdsub_0_mult_out_rob_1_8;
    wire muladdsub_0_mult_out_roa_1_8;
    wire muladdsub_0_mult_out_rob_1_7;
    wire muladdsub_0_mult_out_roa_1_7;
    wire muladdsub_0_mult_out_rob_1_6;
    wire muladdsub_0_mult_out_roa_1_6;
    wire muladdsub_0_mult_out_rob_1_5;
    wire muladdsub_0_mult_out_roa_1_5;
    wire muladdsub_0_mult_out_rob_1_4;
    wire muladdsub_0_mult_out_roa_1_4;
    wire muladdsub_0_mult_out_rob_1_3;
    wire muladdsub_0_mult_out_roa_1_3;
    wire muladdsub_0_mult_out_rob_1_2;
    wire muladdsub_0_mult_out_roa_1_2;
    wire muladdsub_0_mult_out_rob_1_1;
    wire muladdsub_0_mult_out_roa_1_1;
    wire muladdsub_0_mult_out_rob_1_0;
    wire muladdsub_0_mult_out_roa_1_0;
    wire muladdsub_0_mult_out_p_1_35;
    wire muladdsub_0_mult_out_p_1_34;
    wire muladdsub_0_mult_out_p_1_33;
    wire muladdsub_0_mult_out_p_1_32;
    wire muladdsub_0_mult_out_p_1_31;
    wire muladdsub_0_mult_out_p_1_30;
    wire muladdsub_0_mult_out_p_1_29;
    wire muladdsub_0_mult_out_p_1_28;
    wire muladdsub_0_mult_out_p_1_27;
    wire muladdsub_0_mult_out_p_1_26;
    wire muladdsub_0_mult_out_p_1_25;
    wire muladdsub_0_mult_out_p_1_24;
    wire muladdsub_0_mult_out_p_1_23;
    wire muladdsub_0_mult_out_p_1_22;
    wire muladdsub_0_mult_out_p_1_21;
    wire muladdsub_0_mult_out_p_1_20;
    wire muladdsub_0_mult_out_p_1_19;
    wire muladdsub_0_mult_out_p_1_18;
    wire muladdsub_0_mult_out_p_1_17;
    wire muladdsub_0_mult_out_p_1_16;
    wire muladdsub_0_mult_out_p_1_15;
    wire muladdsub_0_mult_out_p_1_14;
    wire muladdsub_0_mult_out_p_1_13;
    wire muladdsub_0_mult_out_p_1_12;
    wire muladdsub_0_mult_out_p_1_11;
    wire muladdsub_0_mult_out_p_1_10;
    wire muladdsub_0_mult_out_p_1_9;
    wire muladdsub_0_mult_out_p_1_8;
    wire muladdsub_0_mult_out_p_1_7;
    wire muladdsub_0_mult_out_p_1_6;
    wire muladdsub_0_mult_out_p_1_5;
    wire muladdsub_0_mult_out_p_1_4;
    wire muladdsub_0_mult_out_p_1_3;
    wire muladdsub_0_mult_out_p_1_2;
    wire muladdsub_0_mult_out_p_1_1;
    wire muladdsub_0_mult_out_p_1_0;
    wire muladdsub_0_mult_out_signedp_1;
    wire scuba_vhi;
    wire scuba_vlo;

    INV INV_0 (.A(ADDNSUB), .Z(addsub_inv));

    defparam dsp_alu_0.CLK3_DIV = "ENABLED" ;
    defparam dsp_alu_0.CLK2_DIV = "ENABLED" ;
    defparam dsp_alu_0.CLK1_DIV = "ENABLED" ;
    defparam dsp_alu_0.CLK0_DIV = "ENABLED" ;
    defparam dsp_alu_0.REG_INPUTCFB_RST = "RST0" ;
    defparam dsp_alu_0.REG_INPUTCFB_CE = "CE0" ;
    defparam dsp_alu_0.REG_INPUTCFB_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEIN_1_RST = "RST0" ;
    defparam dsp_alu_0.REG_OPCODEIN_1_CE = "CE0" ;
    defparam dsp_alu_0.REG_OPCODEIN_1_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEIN_0_RST = "RST0" ;
    defparam dsp_alu_0.REG_OPCODEIN_0_CE = "CE0" ;
    defparam dsp_alu_0.REG_OPCODEIN_0_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEOP1_1_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEOP1_0_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEOP0_1_RST = "RST0" ;
    defparam dsp_alu_0.REG_OPCODEOP0_1_CE = "CE1" ;
    defparam dsp_alu_0.REG_OPCODEOP0_1_CLK = "CLK0" ;
    defparam dsp_alu_0.REG_OPCODEOP0_0_RST = "RST0" ;
    defparam dsp_alu_0.REG_OPCODEOP0_0_CE = "CE1" ;
    defparam dsp_alu_0.REG_OPCODEOP0_0_CLK = "CLK0" ;
    defparam dsp_alu_0.REG_INPUTC1_RST = "RST0" ;
    defparam dsp_alu_0.REG_INPUTC1_CE = "CE0" ;
    defparam dsp_alu_0.REG_INPUTC1_CLK = "NONE" ;
    defparam dsp_alu_0.REG_INPUTC0_RST = "RST0" ;
    defparam dsp_alu_0.REG_INPUTC0_CE = "CE0" ;
    defparam dsp_alu_0.REG_INPUTC0_CLK = "NONE" ;
    defparam dsp_alu_0.LEGACY = "ENABLED" ;
    defparam dsp_alu_0.REG_FLAG_RST = "RST0" ;
    defparam dsp_alu_0.REG_FLAG_CE = "CE2" ;
    defparam dsp_alu_0.REG_FLAG_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OUTPUT1_RST = "RST0" ;
    defparam dsp_alu_0.REG_OUTPUT1_CE = "CE2" ;
    defparam dsp_alu_0.REG_OUTPUT1_CLK = "CLK0" ;
    defparam dsp_alu_0.REG_OUTPUT0_RST = "RST0" ;
    defparam dsp_alu_0.REG_OUTPUT0_CE = "CE2" ;
    defparam dsp_alu_0.REG_OUTPUT0_CLK = "CLK0" ;
    defparam dsp_alu_0.MULT9_MODE = "DISABLED" ;
    defparam dsp_alu_0.RNDPAT = "0x00000000000000" ;
    defparam dsp_alu_0.MASKPAT = "0x00000000000000" ;
    defparam dsp_alu_0.MCPAT = "0x00000000000000" ;
    defparam dsp_alu_0.MASK01 = "0x00000000000000" ;
    defparam dsp_alu_0.MASKPAT_SOURCE = "STATIC" ;
    defparam dsp_alu_0.MCPAT_SOURCE = "STATIC" ;
    defparam dsp_alu_0.RESETMODE = "ASYNC" ;
    defparam dsp_alu_0.GSR = "ENABLED" ;
    ALU54B dsp_alu_0 (.A35(muladdsub_0_mult_out_rob_0_17), .A34(muladdsub_0_mult_out_rob_0_16),
        .A33(muladdsub_0_mult_out_rob_0_15), .A32(muladdsub_0_mult_out_rob_0_14),
        .A31(muladdsub_0_mult_out_rob_0_13), .A30(muladdsub_0_mult_out_rob_0_12),
        .A29(muladdsub_0_mult_out_rob_0_11), .A28(muladdsub_0_mult_out_rob_0_10),
        .A27(muladdsub_0_mult_out_rob_0_9), .A26(muladdsub_0_mult_out_rob_0_8),
        .A25(muladdsub_0_mult_out_rob_0_7), .A24(muladdsub_0_mult_out_rob_0_6),
        .A23(muladdsub_0_mult_out_rob_0_5), .A22(muladdsub_0_mult_out_rob_0_4),
        .A21(muladdsub_0_mult_out_rob_0_3), .A20(muladdsub_0_mult_out_rob_0_2),
        .A19(muladdsub_0_mult_out_rob_0_1), .A18(muladdsub_0_mult_out_rob_0_0),
        .A17(muladdsub_0_mult_out_roa_0_17), .A16(muladdsub_0_mult_out_roa_0_16),
        .A15(muladdsub_0_mult_out_roa_0_15), .A14(muladdsub_0_mult_out_roa_0_14),
        .A13(muladdsub_0_mult_out_roa_0_13), .A12(muladdsub_0_mult_out_roa_0_12),
        .A11(muladdsub_0_mult_out_roa_0_11), .A10(muladdsub_0_mult_out_roa_0_10),
        .A9(muladdsub_0_mult_out_roa_0_9), .A8(muladdsub_0_mult_out_roa_0_8),
        .A7(muladdsub_0_mult_out_roa_0_7), .A6(muladdsub_0_mult_out_roa_0_6),
        .A5(muladdsub_0_mult_out_roa_0_5), .A4(muladdsub_0_mult_out_roa_0_4),
        .A3(muladdsub_0_mult_out_roa_0_3), .A2(muladdsub_0_mult_out_roa_0_2),
        .A1(muladdsub_0_mult_out_roa_0_1), .A0(muladdsub_0_mult_out_roa_0_0),
        .B35(muladdsub_0_mult_out_rob_1_17), .B34(muladdsub_0_mult_out_rob_1_16),
        .B33(muladdsub_0_mult_out_rob_1_15), .B32(muladdsub_0_mult_out_rob_1_14),
        .B31(muladdsub_0_mult_out_rob_1_13), .B30(muladdsub_0_mult_out_rob_1_12),
        .B29(muladdsub_0_mult_out_rob_1_11), .B28(muladdsub_0_mult_out_rob_1_10),
        .B27(muladdsub_0_mult_out_rob_1_9), .B26(muladdsub_0_mult_out_rob_1_8),
        .B25(muladdsub_0_mult_out_rob_1_7), .B24(muladdsub_0_mult_out_rob_1_6),
        .B23(muladdsub_0_mult_out_rob_1_5), .B22(muladdsub_0_mult_out_rob_1_4),
        .B21(muladdsub_0_mult_out_rob_1_3), .B20(muladdsub_0_mult_out_rob_1_2),
        .B19(muladdsub_0_mult_out_rob_1_1), .B18(muladdsub_0_mult_out_rob_1_0),
        .B17(muladdsub_0_mult_out_roa_1_17), .B16(muladdsub_0_mult_out_roa_1_16),
        .B15(muladdsub_0_mult_out_roa_1_15), .B14(muladdsub_0_mult_out_roa_1_14),
        .B13(muladdsub_0_mult_out_roa_1_13), .B12(muladdsub_0_mult_out_roa_1_12),
        .B11(muladdsub_0_mult_out_roa_1_11), .B10(muladdsub_0_mult_out_roa_1_10),
        .B9(muladdsub_0_mult_out_roa_1_9), .B8(muladdsub_0_mult_out_roa_1_8),
        .B7(muladdsub_0_mult_out_roa_1_7), .B6(muladdsub_0_mult_out_roa_1_6),
        .B5(muladdsub_0_mult_out_roa_1_5), .B4(muladdsub_0_mult_out_roa_1_4),
        .B3(muladdsub_0_mult_out_roa_1_3), .B2(muladdsub_0_mult_out_roa_1_2),
        .B1(muladdsub_0_mult_out_roa_1_1), .B0(muladdsub_0_mult_out_roa_1_0),
        .CFB53(scuba_vlo), .CFB52(scuba_vlo), .CFB51(scuba_vlo), .CFB50(scuba_vlo),
        .CFB49(scuba_vlo), .CFB48(scuba_vlo), .CFB47(scuba_vlo), .CFB46(scuba_vlo),
        .CFB45(scuba_vlo), .CFB44(scuba_vlo), .CFB43(scuba_vlo), .CFB42(scuba_vlo),
        .CFB41(scuba_vlo), .CFB40(scuba_vlo), .CFB39(scuba_vlo), .CFB38(scuba_vlo),
        .CFB37(scuba_vlo), .CFB36(scuba_vlo), .CFB35(scuba_vlo), .CFB34(scuba_vlo),
        .CFB33(scuba_vlo), .CFB32(scuba_vlo), .CFB31(scuba_vlo), .CFB30(scuba_vlo),
        .CFB29(scuba_vlo), .CFB28(scuba_vlo), .CFB27(scuba_vlo), .CFB26(scuba_vlo),
        .CFB25(scuba_vlo), .CFB24(scuba_vlo), .CFB23(scuba_vlo), .CFB22(scuba_vlo),
        .CFB21(scuba_vlo), .CFB20(scuba_vlo), .CFB19(scuba_vlo), .CFB18(scuba_vlo),
        .CFB17(scuba_vlo), .CFB16(scuba_vlo), .CFB15(scuba_vlo), .CFB14(scuba_vlo),
        .CFB13(scuba_vlo), .CFB12(scuba_vlo), .CFB11(scuba_vlo), .CFB10(scuba_vlo),
        .CFB9(scuba_vlo), .CFB8(scuba_vlo), .CFB7(scuba_vlo), .CFB6(scuba_vlo),
        .CFB5(scuba_vlo), .CFB4(scuba_vlo), .CFB3(scuba_vlo), .CFB2(scuba_vlo),
        .CFB1(scuba_vlo), .CFB0(scuba_vlo), .C53(scuba_vlo), .C52(scuba_vlo),
        .C51(scuba_vlo), .C50(scuba_vlo), .C49(scuba_vlo), .C48(scuba_vlo),
        .C47(scuba_vlo), .C46(scuba_vlo), .C45(scuba_vlo), .C44(scuba_vlo),
        .C43(scuba_vlo), .C42(scuba_vlo), .C41(scuba_vlo), .C40(scuba_vlo),
        .C39(scuba_vlo), .C38(scuba_vlo), .C37(scuba_vlo), .C36(scuba_vlo),
        .C35(scuba_vlo), .C34(scuba_vlo), .C33(scuba_vlo), .C32(scuba_vlo),
        .C31(scuba_vlo), .C30(scuba_vlo), .C29(scuba_vlo), .C28(scuba_vlo),
        .C27(scuba_vlo), .C26(scuba_vlo), .C25(scuba_vlo), .C24(scuba_vlo),
        .C23(scuba_vlo), .C22(scuba_vlo), .C21(scuba_vlo), .C20(scuba_vlo),
        .C19(scuba_vlo), .C18(scuba_vlo), .C17(scuba_vlo), .C16(scuba_vlo),
        .C15(scuba_vlo), .C14(scuba_vlo), .C13(scuba_vlo), .C12(scuba_vlo),
        .C11(scuba_vlo), .C10(scuba_vlo), .C9(scuba_vlo), .C8(scuba_vlo),
        .C7(scuba_vlo), .C6(scuba_vlo), .C5(scuba_vlo), .C4(scuba_vlo),
        .C3(scuba_vlo), .C2(scuba_vlo), .C1(scuba_vlo), .C0(scuba_vlo),
        .CE0(CE0), .CE1(CE1), .CE2(CE2), .CE3(scuba_vhi), .CLK0(CLK0), .CLK1(scuba_vlo),
        .CLK2(scuba_vlo), .CLK3(scuba_vlo), .RST0(RST0), .RST1(scuba_vlo),
        .RST2(scuba_vlo), .RST3(scuba_vlo), .SIGNEDIA(muladdsub_0_mult_out_signedp_0),
        .SIGNEDIB(muladdsub_0_mult_out_signedp_1), .SIGNEDCIN(muladdsub_alu_signedcin_1_0),
        .MA35(muladdsub_0_mult_out_p_0_35), .MA34(muladdsub_0_mult_out_p_0_34),
        .MA33(muladdsub_0_mult_out_p_0_33), .MA32(muladdsub_0_mult_out_p_0_32),
        .MA31(muladdsub_0_mult_out_p_0_31), .MA30(muladdsub_0_mult_out_p_0_30),
        .MA29(muladdsub_0_mult_out_p_0_29), .MA28(muladdsub_0_mult_out_p_0_28),
        .MA27(muladdsub_0_mult_out_p_0_27), .MA26(muladdsub_0_mult_out_p_0_26),
        .MA25(muladdsub_0_mult_out_p_0_25), .MA24(muladdsub_0_mult_out_p_0_24),
        .MA23(muladdsub_0_mult_out_p_0_23), .MA22(muladdsub_0_mult_out_p_0_22),
        .MA21(muladdsub_0_mult_out_p_0_21), .MA20(muladdsub_0_mult_out_p_0_20),
        .MA19(muladdsub_0_mult_out_p_0_19), .MA18(muladdsub_0_mult_out_p_0_18),
        .MA17(muladdsub_0_mult_out_p_0_17), .MA16(muladdsub_0_mult_out_p_0_16),
        .MA15(muladdsub_0_mult_out_p_0_15), .MA14(muladdsub_0_mult_out_p_0_14),
        .MA13(muladdsub_0_mult_out_p_0_13), .MA12(muladdsub_0_mult_out_p_0_12),
        .MA11(muladdsub_0_mult_out_p_0_11), .MA10(muladdsub_0_mult_out_p_0_10),
        .MA9(muladdsub_0_mult_out_p_0_9), .MA8(muladdsub_0_mult_out_p_0_8),
        .MA7(muladdsub_0_mult_out_p_0_7), .MA6(muladdsub_0_mult_out_p_0_6),
        .MA5(muladdsub_0_mult_out_p_0_5), .MA4(muladdsub_0_mult_out_p_0_4),
        .MA3(muladdsub_0_mult_out_p_0_3), .MA2(muladdsub_0_mult_out_p_0_2),
        .MA1(muladdsub_0_mult_out_p_0_1), .MA0(muladdsub_0_mult_out_p_0_0),
        .MB35(muladdsub_0_mult_out_p_1_35), .MB34(muladdsub_0_mult_out_p_1_34),
        .MB33(muladdsub_0_mult_out_p_1_33), .MB32(muladdsub_0_mult_out_p_1_32),
        .MB31(muladdsub_0_mult_out_p_1_31), .MB30(muladdsub_0_mult_out_p_1_30),
        .MB29(muladdsub_0_mult_out_p_1_29), .MB28(muladdsub_0_mult_out_p_1_28),
        .MB27(muladdsub_0_mult_out_p_1_27), .MB26(muladdsub_0_mult_out_p_1_26),
        .MB25(muladdsub_0_mult_out_p_1_25), .MB24(muladdsub_0_mult_out_p_1_24),
        .MB23(muladdsub_0_mult_out_p_1_23), .MB22(muladdsub_0_mult_out_p_1_22),
        .MB21(muladdsub_0_mult_out_p_1_21), .MB20(muladdsub_0_mult_out_p_1_20),
        .MB19(muladdsub_0_mult_out_p_1_19), .MB18(muladdsub_0_mult_out_p_1_18),
        .MB17(muladdsub_0_mult_out_p_1_17), .MB16(muladdsub_0_mult_out_p_1_16),
        .MB15(muladdsub_0_mult_out_p_1_15), .MB14(muladdsub_0_mult_out_p_1_14),
        .MB13(muladdsub_0_mult_out_p_1_13), .MB12(muladdsub_0_mult_out_p_1_12),
        .MB11(muladdsub_0_mult_out_p_1_11), .MB10(muladdsub_0_mult_out_p_1_10),
        .MB9(muladdsub_0_mult_out_p_1_9), .MB8(muladdsub_0_mult_out_p_1_8),
        .MB7(muladdsub_0_mult_out_p_1_7), .MB6(muladdsub_0_mult_out_p_1_6),
        .MB5(muladdsub_0_mult_out_p_1_5), .MB4(muladdsub_0_mult_out_p_1_4),
        .MB3(muladdsub_0_mult_out_p_1_3), .MB2(muladdsub_0_mult_out_p_1_2),
        .MB1(muladdsub_0_mult_out_p_1_1), .MB0(muladdsub_0_mult_out_p_1_0),
        .CIN53(muladdsub_alu_in_cin_1_0_53), .CIN52(muladdsub_alu_in_cin_1_0_52),
        .CIN51(muladdsub_alu_in_cin_1_0_51), .CIN50(muladdsub_alu_in_cin_1_0_50),
        .CIN49(muladdsub_alu_in_cin_1_0_49), .CIN48(muladdsub_alu_in_cin_1_0_48),
        .CIN47(muladdsub_alu_in_cin_1_0_47), .CIN46(muladdsub_alu_in_cin_1_0_46),
        .CIN45(muladdsub_alu_in_cin_1_0_45), .CIN44(muladdsub_alu_in_cin_1_0_44),
        .CIN43(muladdsub_alu_in_cin_1_0_43), .CIN42(muladdsub_alu_in_cin_1_0_42),
        .CIN41(muladdsub_alu_in_cin_1_0_41), .CIN40(muladdsub_alu_in_cin_1_0_40),
        .CIN39(muladdsub_alu_in_cin_1_0_39), .CIN38(muladdsub_alu_in_cin_1_0_38),
        .CIN37(muladdsub_alu_in_cin_1_0_37), .CIN36(muladdsub_alu_in_cin_1_0_36),
        .CIN35(muladdsub_alu_in_cin_1_0_35), .CIN34(muladdsub_alu_in_cin_1_0_34),
        .CIN33(muladdsub_alu_in_cin_1_0_33), .CIN32(muladdsub_alu_in_cin_1_0_32),
        .CIN31(muladdsub_alu_in_cin_1_0_31), .CIN30(muladdsub_alu_in_cin_1_0_30),
        .CIN29(muladdsub_alu_in_cin_1_0_29), .CIN28(muladdsub_alu_in_cin_1_0_28),
        .CIN27(muladdsub_alu_in_cin_1_0_27), .CIN26(muladdsub_alu_in_cin_1_0_26),
        .CIN25(muladdsub_alu_in_cin_1_0_25), .CIN24(muladdsub_alu_in_cin_1_0_24),
        .CIN23(muladdsub_alu_in_cin_1_0_23), .CIN22(muladdsub_alu_in_cin_1_0_22),
        .CIN21(muladdsub_alu_in_cin_1_0_21), .CIN20(muladdsub_alu_in_cin_1_0_20),
        .CIN19(muladdsub_alu_in_cin_1_0_19), .CIN18(muladdsub_alu_in_cin_1_0_18),
        .CIN17(muladdsub_alu_in_cin_1_0_17), .CIN16(muladdsub_alu_in_cin_1_0_16),
        .CIN15(muladdsub_alu_in_cin_1_0_15), .CIN14(muladdsub_alu_in_cin_1_0_14),
        .CIN13(muladdsub_alu_in_cin_1_0_13), .CIN12(muladdsub_alu_in_cin_1_0_12),
        .CIN11(muladdsub_alu_in_cin_1_0_11), .CIN10(muladdsub_alu_in_cin_1_0_10),
        .CIN9(muladdsub_alu_in_cin_1_0_9), .CIN8(muladdsub_alu_in_cin_1_0_8),
        .CIN7(muladdsub_alu_in_cin_1_0_7), .CIN6(muladdsub_alu_in_cin_1_0_6),
        .CIN5(muladdsub_alu_in_cin_1_0_5), .CIN4(muladdsub_alu_in_cin_1_0_4),
        .CIN3(muladdsub_alu_in_cin_1_0_3), .CIN2(muladdsub_alu_in_cin_1_0_2),
        .CIN1(muladdsub_alu_in_cin_1_0_1), .CIN0(muladdsub_alu_in_cin_1_0_0),
        .OP10(scuba_vlo), .OP9(scuba_vhi), .OP8(scuba_vlo), .OP7(addsub_inv),
        .OP6(scuba_vlo), .OP5(scuba_vlo), .OP4(scuba_vlo), .OP3(scuba_vlo),
        .OP2(scuba_vhi), .OP1(scuba_vlo), .OP0(scuba_vhi), .R53(muladdsub_alu_output_r_1_0_53),
        .R52(muladdsub_alu_output_r_1_0_52), .R51(muladdsub_alu_output_r_1_0_51),
        .R50(muladdsub_alu_output_r_1_0_50), .R49(muladdsub_alu_output_r_1_0_49),
        .R48(muladdsub_alu_output_r_1_0_48), .R47(muladdsub_alu_output_r_1_0_47),
        .R46(muladdsub_alu_output_r_1_0_46), .R45(muladdsub_alu_output_r_1_0_45),
        .R44(muladdsub_alu_output_r_1_0_44), .R43(muladdsub_alu_output_r_1_0_43),
        .R42(muladdsub_alu_output_r_1_0_42), .R41(muladdsub_alu_output_r_1_0_41),
        .R40(muladdsub_alu_output_r_1_0_40), .R39(muladdsub_alu_output_r_1_0_39),
        .R38(muladdsub_alu_output_r_1_0_38), .R37(muladdsub_alu_output_r_1_0_37),
        .R36(muladdsub_alu_output_r_1_0_36), .R35(muladdsub_alu_output_r_1_0_35),
        .R34(muladdsub_alu_output_r_1_0_34), .R33(muladdsub_alu_output_r_1_0_33),
        .R32(muladdsub_alu_output_r_1_0_32), .R31(muladdsub_alu_output_r_1_0_31),
        .R30(muladdsub_alu_output_r_1_0_30), .R29(muladdsub_alu_output_r_1_0_29),
        .R28(muladdsub_alu_output_r_1_0_28), .R27(muladdsub_alu_output_r_1_0_27),
        .R26(muladdsub_alu_output_r_1_0_26), .R25(muladdsub_alu_output_r_1_0_25),
        .R24(muladdsub_alu_output_r_1_0_24), .R23(muladdsub_alu_output_r_1_0_23),
        .R22(muladdsub_alu_output_r_1_0_22), .R21(muladdsub_alu_output_r_1_0_21),
        .R20(muladdsub_alu_output_r_1_0_20), .R19(muladdsub_alu_output_r_1_0_19),
        .R18(muladdsub_alu_output_r_1_0_18), .R17(muladdsub_alu_output_r_1_0_17),
        .R16(muladdsub_alu_output_r_1_0_16), .R15(muladdsub_alu_output_r_1_0_15),
        .R14(muladdsub_alu_output_r_1_0_14), .R13(muladdsub_alu_output_r_1_0_13),
        .R12(muladdsub_alu_output_r_1_0_12), .R11(muladdsub_alu_output_r_1_0_11),
        .R10(muladdsub_alu_output_r_1_0_10), .R9(muladdsub_alu_output_r_1_0_9),
        .R8(muladdsub_alu_output_r_1_0_8), .R7(muladdsub_alu_output_r_1_0_7),
        .R6(muladdsub_alu_output_r_1_0_6), .R5(muladdsub_alu_output_r_1_0_5),
        .R4(muladdsub_alu_output_r_1_0_4), .R3(muladdsub_alu_output_r_1_0_3),
        .R2(muladdsub_alu_output_r_1_0_2), .R1(muladdsub_alu_output_r_1_0_1),
        .R0(muladdsub_alu_output_r_1_0_0), .CO53(), .CO52(), .CO51(), .CO50(),
        .CO49(), .CO48(), .CO47(), .CO46(), .CO45(), .CO44(), .CO43(), .CO42(),
        .CO41(), .CO40(), .CO39(), .CO38(), .CO37(), .CO36(), .CO35(), .CO34(),
        .CO33(), .CO32(), .CO31(), .CO30(), .CO29(), .CO28(), .CO27(), .CO26(),
        .CO25(), .CO24(), .CO23(), .CO22(), .CO21(), .CO20(), .CO19(), .CO18(),
        .CO17(), .CO16(), .CO15(), .CO14(), .CO13(), .CO12(), .CO11(), .CO10(),
        .CO9(), .CO8(), .CO7(), .CO6(), .CO5(), .CO4(), .CO3(), .CO2(),
        .CO1(), .CO0(), .EQZ(), .EQZM(), .EQOM(), .EQPAT(), .EQPATB(), .OVER(),
        .UNDER(), .OVERUNDER(), .SIGNEDR(muladdsub_alu_signedr_1_0));

    defparam dsp_mult_1.CLK3_DIV = "ENABLED" ;
    defparam dsp_mult_1.CLK2_DIV = "ENABLED" ;
    defparam dsp_mult_1.CLK1_DIV = "ENABLED" ;
    defparam dsp_mult_1.CLK0_DIV = "ENABLED" ;
    defparam dsp_mult_1.HIGHSPEED_CLK = "NONE" ;
    defparam dsp_mult_1.REG_INPUTC_RST = "RST0" ;
    defparam dsp_mult_1.REG_INPUTC_CE = "CE0" ;
    defparam dsp_mult_1.REG_INPUTC_CLK = "NONE" ;
    defparam dsp_mult_1.SOURCEB_MODE = "B_SHIFT" ;
    defparam dsp_mult_1.MULT_BYPASS = "DISABLED" ;
    defparam dsp_mult_1.CAS_MATCH_REG = "FALSE" ;
    defparam dsp_mult_1.RESETMODE = "ASYNC" ;
    defparam dsp_mult_1.GSR = "ENABLED" ;
    defparam dsp_mult_1.REG_OUTPUT_RST = "RST0" ;
    defparam dsp_mult_1.REG_OUTPUT_CE = "CE2" ;
    defparam dsp_mult_1.REG_OUTPUT_CLK = "NONE" ;
    defparam dsp_mult_1.REG_PIPELINE_RST = "RST0" ;
    defparam dsp_mult_1.REG_PIPELINE_CE = "CE1" ;
    defparam dsp_mult_1.REG_PIPELINE_CLK = "CLK0" ;
    defparam dsp_mult_1.REG_INPUTB_RST = "RST0" ;
    defparam dsp_mult_1.REG_INPUTB_CE = "CE0" ;
    defparam dsp_mult_1.REG_INPUTB_CLK = "CLK0" ;
    defparam dsp_mult_1.REG_INPUTA_RST = "RST0" ;
    defparam dsp_mult_1.REG_INPUTA_CE = "CE0" ;
    defparam dsp_mult_1.REG_INPUTA_CLK = "CLK0" ;
    MULT18X18D dsp_mult_1 (.A17(A0[17]), .A16(A0[16]), .A15(A0[15]), .A14(A0[14]),
        .A13(A0[13]), .A12(A0[12]), .A11(A0[11]), .A10(A0[10]), .A9(A0[9]),
        .A8(A0[8]), .A7(A0[7]), .A6(A0[6]), .A5(A0[5]), .A4(A0[4]), .A3(A0[3]),
        .A2(A0[2]), .A1(A0[1]), .A0(A0[0]), .B17(B0[17]), .B16(B0[16]),
        .B15(B0[15]), .B14(B0[14]), .B13(B0[13]), .B12(B0[12]), .B11(B0[11]),
        .B10(B0[10]), .B9(B0[9]), .B8(B0[8]), .B7(B0[7]), .B6(B0[6]), .B5(B0[5]),
        .B4(B0[4]), .B3(B0[3]), .B2(B0[2]), .B1(B0[1]), .B0(B0[0]), .C17(scuba_vlo),
        .C16(scuba_vlo), .C15(scuba_vlo), .C14(scuba_vlo), .C13(scuba_vlo),
        .C12(scuba_vlo), .C11(scuba_vlo), .C10(scuba_vlo), .C9(scuba_vlo),
        .C8(scuba_vlo), .C7(scuba_vlo), .C6(scuba_vlo), .C5(scuba_vlo),
        .C4(scuba_vlo), .C3(scuba_vlo), .C2(scuba_vlo), .C1(scuba_vlo),
        .C0(scuba_vlo), .SIGNEDA(scuba_vhi), .SIGNEDB(scuba_vhi), .SOURCEA(scuba_vlo),
        .SOURCEB(scuba_vlo), .CE0(CE0), .CE1(CE1), .CE2(CE2), .CE3(scuba_vhi),
        .CLK0(CLK0), .CLK1(scuba_vlo), .CLK2(scuba_vlo), .CLK3(scuba_vlo),
        .RST0(RST0), .RST1(scuba_vlo), .RST2(scuba_vlo), .RST3(scuba_vlo),
        .SRIA17(scuba_vlo), .SRIA16(scuba_vlo), .SRIA15(scuba_vlo), .SRIA14(scuba_vlo),
        .SRIA13(scuba_vlo), .SRIA12(scuba_vlo), .SRIA11(scuba_vlo), .SRIA10(scuba_vlo),
        .SRIA9(scuba_vlo), .SRIA8(scuba_vlo), .SRIA7(scuba_vlo), .SRIA6(scuba_vlo),
        .SRIA5(scuba_vlo), .SRIA4(scuba_vlo), .SRIA3(scuba_vlo), .SRIA2(scuba_vlo),
        .SRIA1(scuba_vlo), .SRIA0(scuba_vlo), .SRIB17(scuba_vlo), .SRIB16(scuba_vlo),
        .SRIB15(scuba_vlo), .SRIB14(scuba_vlo), .SRIB13(scuba_vlo), .SRIB12(scuba_vlo),
        .SRIB11(scuba_vlo), .SRIB10(scuba_vlo), .SRIB9(scuba_vlo), .SRIB8(scuba_vlo),
        .SRIB7(scuba_vlo), .SRIB6(scuba_vlo), .SRIB5(scuba_vlo), .SRIB4(scuba_vlo),
        .SRIB3(scuba_vlo), .SRIB2(scuba_vlo), .SRIB1(scuba_vlo), .SRIB0(scuba_vlo),
        .SROA17(), .SROA16(), .SROA15(), .SROA14(), .SROA13(), .SROA12(),
        .SROA11(), .SROA10(), .SROA9(), .SROA8(), .SROA7(), .SROA6(), .SROA5(),
        .SROA4(), .SROA3(), .SROA2(), .SROA1(), .SROA0(), .SROB17(), .SROB16(),
        .SROB15(), .SROB14(), .SROB13(), .SROB12(), .SROB11(), .SROB10(),
        .SROB9(), .SROB8(), .SROB7(), .SROB6(), .SROB5(), .SROB4(), .SROB3(),
        .SROB2(), .SROB1(), .SROB0(), .ROA17(muladdsub_0_mult_out_roa_0_17),
        .ROA16(muladdsub_0_mult_out_roa_0_16), .ROA15(muladdsub_0_mult_out_roa_0_15),
        .ROA14(muladdsub_0_mult_out_roa_0_14), .ROA13(muladdsub_0_mult_out_roa_0_13),
        .ROA12(muladdsub_0_mult_out_roa_0_12), .ROA11(muladdsub_0_mult_out_roa_0_11),
        .ROA10(muladdsub_0_mult_out_roa_0_10), .ROA9(muladdsub_0_mult_out_roa_0_9),
        .ROA8(muladdsub_0_mult_out_roa_0_8), .ROA7(muladdsub_0_mult_out_roa_0_7),
        .ROA6(muladdsub_0_mult_out_roa_0_6), .ROA5(muladdsub_0_mult_out_roa_0_5),
        .ROA4(muladdsub_0_mult_out_roa_0_4), .ROA3(muladdsub_0_mult_out_roa_0_3),
        .ROA2(muladdsub_0_mult_out_roa_0_2), .ROA1(muladdsub_0_mult_out_roa_0_1),
        .ROA0(muladdsub_0_mult_out_roa_0_0), .ROB17(muladdsub_0_mult_out_rob_0_17),
        .ROB16(muladdsub_0_mult_out_rob_0_16), .ROB15(muladdsub_0_mult_out_rob_0_15),
        .ROB14(muladdsub_0_mult_out_rob_0_14), .ROB13(muladdsub_0_mult_out_rob_0_13),
        .ROB12(muladdsub_0_mult_out_rob_0_12), .ROB11(muladdsub_0_mult_out_rob_0_11),
        .ROB10(muladdsub_0_mult_out_rob_0_10), .ROB9(muladdsub_0_mult_out_rob_0_9),
        .ROB8(muladdsub_0_mult_out_rob_0_8), .ROB7(muladdsub_0_mult_out_rob_0_7),
        .ROB6(muladdsub_0_mult_out_rob_0_6), .ROB5(muladdsub_0_mult_out_rob_0_5),
        .ROB4(muladdsub_0_mult_out_rob_0_4), .ROB3(muladdsub_0_mult_out_rob_0_3),
        .ROB2(muladdsub_0_mult_out_rob_0_2), .ROB1(muladdsub_0_mult_out_rob_0_1),
        .ROB0(muladdsub_0_mult_out_rob_0_0), .ROC17(), .ROC16(), .ROC15(),
        .ROC14(), .ROC13(), .ROC12(), .ROC11(), .ROC10(), .ROC9(), .ROC8(),
        .ROC7(), .ROC6(), .ROC5(), .ROC4(), .ROC3(), .ROC2(), .ROC1(), .ROC0(),
        .P35(muladdsub_0_mult_out_p_0_35), .P34(muladdsub_0_mult_out_p_0_34),
        .P33(muladdsub_0_mult_out_p_0_33), .P32(muladdsub_0_mult_out_p_0_32),
        .P31(muladdsub_0_mult_out_p_0_31), .P30(muladdsub_0_mult_out_p_0_30),
        .P29(muladdsub_0_mult_out_p_0_29), .P28(muladdsub_0_mult_out_p_0_28),
        .P27(muladdsub_0_mult_out_p_0_27), .P26(muladdsub_0_mult_out_p_0_26),
        .P25(muladdsub_0_mult_out_p_0_25), .P24(muladdsub_0_mult_out_p_0_24),
        .P23(muladdsub_0_mult_out_p_0_23), .P22(muladdsub_0_mult_out_p_0_22),
        .P21(muladdsub_0_mult_out_p_0_21), .P20(muladdsub_0_mult_out_p_0_20),
        .P19(muladdsub_0_mult_out_p_0_19), .P18(muladdsub_0_mult_out_p_0_18),
        .P17(muladdsub_0_mult_out_p_0_17), .P16(muladdsub_0_mult_out_p_0_16),
        .P15(muladdsub_0_mult_out_p_0_15), .P14(muladdsub_0_mult_out_p_0_14),
        .P13(muladdsub_0_mult_out_p_0_13), .P12(muladdsub_0_mult_out_p_0_12),
        .P11(muladdsub_0_mult_out_p_0_11), .P10(muladdsub_0_mult_out_p_0_10),
        .P9(muladdsub_0_mult_out_p_0_9), .P8(muladdsub_0_mult_out_p_0_8),
        .P7(muladdsub_0_mult_out_p_0_7), .P6(muladdsub_0_mult_out_p_0_6),
        .P5(muladdsub_0_mult_out_p_0_5), .P4(muladdsub_0_mult_out_p_0_4),
        .P3(muladdsub_0_mult_out_p_0_3), .P2(muladdsub_0_mult_out_p_0_2),
        .P1(muladdsub_0_mult_out_p_0_1), .P0(muladdsub_0_mult_out_p_0_0),
        .SIGNEDP(muladdsub_0_mult_out_signedp_0));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam dsp_mult_0.CLK3_DIV = "ENABLED" ;
    defparam dsp_mult_0.CLK2_DIV = "ENABLED" ;
    defparam dsp_mult_0.CLK1_DIV = "ENABLED" ;
    defparam dsp_mult_0.CLK0_DIV = "ENABLED" ;
    defparam dsp_mult_0.HIGHSPEED_CLK = "NONE" ;
    defparam dsp_mult_0.REG_INPUTC_RST = "RST0" ;
    defparam dsp_mult_0.REG_INPUTC_CE = "CE0" ;
    defparam dsp_mult_0.REG_INPUTC_CLK = "NONE" ;
    defparam dsp_mult_0.SOURCEB_MODE = "B_SHIFT" ;
    defparam dsp_mult_0.MULT_BYPASS = "DISABLED" ;
    defparam dsp_mult_0.CAS_MATCH_REG = "FALSE" ;
    defparam dsp_mult_0.RESETMODE = "ASYNC" ;
    defparam dsp_mult_0.GSR = "ENABLED" ;
    defparam dsp_mult_0.REG_OUTPUT_RST = "RST0" ;
    defparam dsp_mult_0.REG_OUTPUT_CE = "CE2" ;
    defparam dsp_mult_0.REG_OUTPUT_CLK = "NONE" ;
    defparam dsp_mult_0.REG_PIPELINE_RST = "RST0" ;
    defparam dsp_mult_0.REG_PIPELINE_CE = "CE1" ;
    defparam dsp_mult_0.REG_PIPELINE_CLK = "CLK0" ;
    defparam dsp_mult_0.REG_INPUTB_RST = "RST0" ;
    defparam dsp_mult_0.REG_INPUTB_CE = "CE0" ;
    defparam dsp_mult_0.REG_INPUTB_CLK = "CLK0" ;
    defparam dsp_mult_0.REG_INPUTA_RST = "RST0" ;
    defparam dsp_mult_0.REG_INPUTA_CE = "CE0" ;
    defparam dsp_mult_0.REG_INPUTA_CLK = "CLK0" ;
    MULT18X18D dsp_mult_0 (.A17(A1[17]), .A16(A1[16]), .A15(A1[15]), .A14(A1[14]),
        .A13(A1[13]), .A12(A1[12]), .A11(A1[11]), .A10(A1[10]), .A9(A1[9]),
        .A8(A1[8]), .A7(A1[7]), .A6(A1[6]), .A5(A1[5]), .A4(A1[4]), .A3(A1[3]),
        .A2(A1[2]), .A1(A1[1]), .A0(A1[0]), .B17(B1[17]), .B16(B1[16]),
        .B15(B1[15]), .B14(B1[14]), .B13(B1[13]), .B12(B1[12]), .B11(B1[11]),
        .B10(B1[10]), .B9(B1[9]), .B8(B1[8]), .B7(B1[7]), .B6(B1[6]), .B5(B1[5]),
        .B4(B1[4]), .B3(B1[3]), .B2(B1[2]), .B1(B1[1]), .B0(B1[0]), .C17(scuba_vlo),
        .C16(scuba_vlo), .C15(scuba_vlo), .C14(scuba_vlo), .C13(scuba_vlo),
        .C12(scuba_vlo), .C11(scuba_vlo), .C10(scuba_vlo), .C9(scuba_vlo),
        .C8(scuba_vlo), .C7(scuba_vlo), .C6(scuba_vlo), .C5(scuba_vlo),
        .C4(scuba_vlo), .C3(scuba_vlo), .C2(scuba_vlo), .C1(scuba_vlo),
        .C0(scuba_vlo), .SIGNEDA(scuba_vhi), .SIGNEDB(scuba_vhi), .SOURCEA(scuba_vlo),
        .SOURCEB(scuba_vlo), .CE0(CE0), .CE1(CE1), .CE2(CE2), .CE3(scuba_vhi),
        .CLK0(CLK0), .CLK1(scuba_vlo), .CLK2(scuba_vlo), .CLK3(scuba_vlo),
        .RST0(RST0), .RST1(scuba_vlo), .RST2(scuba_vlo), .RST3(scuba_vlo),
        .SRIA17(scuba_vlo), .SRIA16(scuba_vlo), .SRIA15(scuba_vlo), .SRIA14(scuba_vlo),
        .SRIA13(scuba_vlo), .SRIA12(scuba_vlo), .SRIA11(scuba_vlo), .SRIA10(scuba_vlo),
        .SRIA9(scuba_vlo), .SRIA8(scuba_vlo), .SRIA7(scuba_vlo), .SRIA6(scuba_vlo),
        .SRIA5(scuba_vlo), .SRIA4(scuba_vlo), .SRIA3(scuba_vlo), .SRIA2(scuba_vlo),
        .SRIA1(scuba_vlo), .SRIA0(scuba_vlo), .SRIB17(scuba_vlo), .SRIB16(scuba_vlo),
        .SRIB15(scuba_vlo), .SRIB14(scuba_vlo), .SRIB13(scuba_vlo), .SRIB12(scuba_vlo),
        .SRIB11(scuba_vlo), .SRIB10(scuba_vlo), .SRIB9(scuba_vlo), .SRIB8(scuba_vlo),
        .SRIB7(scuba_vlo), .SRIB6(scuba_vlo), .SRIB5(scuba_vlo), .SRIB4(scuba_vlo),
        .SRIB3(scuba_vlo), .SRIB2(scuba_vlo), .SRIB1(scuba_vlo), .SRIB0(scuba_vlo),
        .SROA17(), .SROA16(), .SROA15(), .SROA14(), .SROA13(), .SROA12(),
        .SROA11(), .SROA10(), .SROA9(), .SROA8(), .SROA7(), .SROA6(), .SROA5(),
        .SROA4(), .SROA3(), .SROA2(), .SROA1(), .SROA0(), .SROB17(), .SROB16(),
        .SROB15(), .SROB14(), .SROB13(), .SROB12(), .SROB11(), .SROB10(),
        .SROB9(), .SROB8(), .SROB7(), .SROB6(), .SROB5(), .SROB4(), .SROB3(),
        .SROB2(), .SROB1(), .SROB0(), .ROA17(muladdsub_0_mult_out_roa_1_17),
        .ROA16(muladdsub_0_mult_out_roa_1_16), .ROA15(muladdsub_0_mult_out_roa_1_15),
        .ROA14(muladdsub_0_mult_out_roa_1_14), .ROA13(muladdsub_0_mult_out_roa_1_13),
        .ROA12(muladdsub_0_mult_out_roa_1_12), .ROA11(muladdsub_0_mult_out_roa_1_11),
        .ROA10(muladdsub_0_mult_out_roa_1_10), .ROA9(muladdsub_0_mult_out_roa_1_9),
        .ROA8(muladdsub_0_mult_out_roa_1_8), .ROA7(muladdsub_0_mult_out_roa_1_7),
        .ROA6(muladdsub_0_mult_out_roa_1_6), .ROA5(muladdsub_0_mult_out_roa_1_5),
        .ROA4(muladdsub_0_mult_out_roa_1_4), .ROA3(muladdsub_0_mult_out_roa_1_3),
        .ROA2(muladdsub_0_mult_out_roa_1_2), .ROA1(muladdsub_0_mult_out_roa_1_1),
        .ROA0(muladdsub_0_mult_out_roa_1_0), .ROB17(muladdsub_0_mult_out_rob_1_17),
        .ROB16(muladdsub_0_mult_out_rob_1_16), .ROB15(muladdsub_0_mult_out_rob_1_15),
        .ROB14(muladdsub_0_mult_out_rob_1_14), .ROB13(muladdsub_0_mult_out_rob_1_13),
        .ROB12(muladdsub_0_mult_out_rob_1_12), .ROB11(muladdsub_0_mult_out_rob_1_11),
        .ROB10(muladdsub_0_mult_out_rob_1_10), .ROB9(muladdsub_0_mult_out_rob_1_9),
        .ROB8(muladdsub_0_mult_out_rob_1_8), .ROB7(muladdsub_0_mult_out_rob_1_7),
        .ROB6(muladdsub_0_mult_out_rob_1_6), .ROB5(muladdsub_0_mult_out_rob_1_5),
        .ROB4(muladdsub_0_mult_out_rob_1_4), .ROB3(muladdsub_0_mult_out_rob_1_3),
        .ROB2(muladdsub_0_mult_out_rob_1_2), .ROB1(muladdsub_0_mult_out_rob_1_1),
        .ROB0(muladdsub_0_mult_out_rob_1_0), .ROC17(), .ROC16(), .ROC15(),
        .ROC14(), .ROC13(), .ROC12(), .ROC11(), .ROC10(), .ROC9(), .ROC8(),
        .ROC7(), .ROC6(), .ROC5(), .ROC4(), .ROC3(), .ROC2(), .ROC1(), .ROC0(),
        .P35(muladdsub_0_mult_out_p_1_35), .P34(muladdsub_0_mult_out_p_1_34),
        .P33(muladdsub_0_mult_out_p_1_33), .P32(muladdsub_0_mult_out_p_1_32),
        .P31(muladdsub_0_mult_out_p_1_31), .P30(muladdsub_0_mult_out_p_1_30),
        .P29(muladdsub_0_mult_out_p_1_29), .P28(muladdsub_0_mult_out_p_1_28),
        .P27(muladdsub_0_mult_out_p_1_27), .P26(muladdsub_0_mult_out_p_1_26),
        .P25(muladdsub_0_mult_out_p_1_25), .P24(muladdsub_0_mult_out_p_1_24),
        .P23(muladdsub_0_mult_out_p_1_23), .P22(muladdsub_0_mult_out_p_1_22),
        .P21(muladdsub_0_mult_out_p_1_21), .P20(muladdsub_0_mult_out_p_1_20),
        .P19(muladdsub_0_mult_out_p_1_19), .P18(muladdsub_0_mult_out_p_1_18),
        .P17(muladdsub_0_mult_out_p_1_17), .P16(muladdsub_0_mult_out_p_1_16),
        .P15(muladdsub_0_mult_out_p_1_15), .P14(muladdsub_0_mult_out_p_1_14),
        .P13(muladdsub_0_mult_out_p_1_13), .P12(muladdsub_0_mult_out_p_1_12),
        .P11(muladdsub_0_mult_out_p_1_11), .P10(muladdsub_0_mult_out_p_1_10),
        .P9(muladdsub_0_mult_out_p_1_9), .P8(muladdsub_0_mult_out_p_1_8),
        .P7(muladdsub_0_mult_out_p_1_7), .P6(muladdsub_0_mult_out_p_1_6),
        .P5(muladdsub_0_mult_out_p_1_5), .P4(muladdsub_0_mult_out_p_1_4),
        .P3(muladdsub_0_mult_out_p_1_3), .P2(muladdsub_0_mult_out_p_1_2),
        .P1(muladdsub_0_mult_out_p_1_1), .P0(muladdsub_0_mult_out_p_1_0),
        .SIGNEDP(muladdsub_0_mult_out_signedp_1));

    // assign SUM[36] = muladdsub_alu_output_r_1_0_36;
    assign SUM[35] = muladdsub_alu_output_r_1_0_35;
    assign SUM[34] = muladdsub_alu_output_r_1_0_34;
    assign SUM[33] = muladdsub_alu_output_r_1_0_33;
    assign SUM[32] = muladdsub_alu_output_r_1_0_32;
    assign SUM[31] = muladdsub_alu_output_r_1_0_31;
    assign SUM[30] = muladdsub_alu_output_r_1_0_30;
    assign SUM[29] = muladdsub_alu_output_r_1_0_29;
    assign SUM[28] = muladdsub_alu_output_r_1_0_28;
    assign SUM[27] = muladdsub_alu_output_r_1_0_27;
    assign SUM[26] = muladdsub_alu_output_r_1_0_26;
    assign SUM[25] = muladdsub_alu_output_r_1_0_25;
    assign SUM[24] = muladdsub_alu_output_r_1_0_24;
    assign SUM[23] = muladdsub_alu_output_r_1_0_23;
    assign SUM[22] = muladdsub_alu_output_r_1_0_22;
    assign SUM[21] = muladdsub_alu_output_r_1_0_21;
    assign SUM[20] = muladdsub_alu_output_r_1_0_20;
    assign SUM[19] = muladdsub_alu_output_r_1_0_19;
    assign SUM[18] = muladdsub_alu_output_r_1_0_18;
    assign SUM[17] = muladdsub_alu_output_r_1_0_17;
    assign SUM[16] = muladdsub_alu_output_r_1_0_16;
    assign SUM[15] = muladdsub_alu_output_r_1_0_15;
    assign SUM[14] = muladdsub_alu_output_r_1_0_14;
    assign SUM[13] = muladdsub_alu_output_r_1_0_13;
    assign SUM[12] = muladdsub_alu_output_r_1_0_12;
    assign SUM[11] = muladdsub_alu_output_r_1_0_11;
    assign SUM[10] = muladdsub_alu_output_r_1_0_10;
    assign SUM[9] = muladdsub_alu_output_r_1_0_9;
    assign SUM[8] = muladdsub_alu_output_r_1_0_8;
    assign SUM[7] = muladdsub_alu_output_r_1_0_7;
    assign SUM[6] = muladdsub_alu_output_r_1_0_6;
    assign SUM[5] = muladdsub_alu_output_r_1_0_5;
    assign SUM[4] = muladdsub_alu_output_r_1_0_4;
    assign SUM[3] = muladdsub_alu_output_r_1_0_3;
    assign SUM[2] = muladdsub_alu_output_r_1_0_2;
    assign SUM[1] = muladdsub_alu_output_r_1_0_1;
    assign SUM[0] = muladdsub_alu_output_r_1_0_0;


    // exemplar begin
    // exemplar end

`endif

endmodule
