HIGGS_ROOT=../../../../../../../../..
Q_ENGINE_REPO=$(HIGGS_ROOT)/lib/hardware/hdl/q-engine
IP_LIBRARY_REPO=$(HIGGS_ROOT)/lib/hardware/hdl/ip-library
RISCV_BASEBAND_REPO=$(HIGGS_ROOT)/lib/rv-software

include $(HIGGS_ROOT)/lib/hardware/make_include/makefile_single_riscv.mk
